id: ICA0790B2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T23:17:40+00:00'
last_modified: '2022-06-08T10:22:42.890644+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4337
  title: བར་དོའི་གསོལ་འདེབས་ཐོས་གྲོལ་ཆེན་མོ་བཀླག་ཆོག་ཏུ་བཀོད་པ་འཁྲུལ་སྣང་རང་གྲོལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0BA8:
      image_group_id: I1KG12069
      title: ''
      total_pages: 358
      order: 1
      base_file: 0BA8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
