id: P009348
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG4337
  title: བར་དོའི་གསོལ་འདེབས་ཐོས་གྲོལ་ཆེན་མོ་བཀླག་ཆོག་ཏུ་བཀོད་པ་འཁྲུལ་སྣང་རང་གྲོལ།
  author: ''
  volumes:
    1cdcd59e218b449684842af667c01a7f:
      image_group_id: I1KG12069
      title: ''
      volume_number: 1
      total_pages: 358
      base_file: v001.txt
